// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodePathHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "267fa06c-a972-428f-9a89-3be2e2dc785a";
        public const string Name = "Code Path Helper";
        public const string Description = @"Makes it super easy to share code path of Azure DevOps, or go to the file given Azure DevOps link.";
        public const string Language = "en-US";
        public const string Version = "1.0.4";
        public const string Author = "Zixuan Wang";
        public const string Tags = "";
    }
}
