// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodePathHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidShareCodePathPackageString = "26edee01-2e53-4882-ab25-139f2a65f65a";
        public static Guid guidShareCodePathPackage = new Guid(guidShareCodePathPackageString);

        public const string guidShareCodePathCmdSetString = "1bf86345-02bf-4028-a183-642081550581";
        public static Guid guidShareCodePathCmdSet = new Guid(guidShareCodePathCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdShareCodePath = 0x0100;
    }
}